name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Build
        run: ./gradlew build
      - name: Test
        run: ./gradlew test
